### ISSUE TITLE
different sort order in firefox & edge, missing 2023

### ISSUE THREAD

**Issue by codydunne** [VisDunneRight/Graph-Layouts#14]
Firefox
![image](https://github.com/VisDunneRight/gd-comp-eval/assets/2694345/c07c77d6-3dba-4c00-bdcd-bab0f07eb112)

Edge
![image](https://github.com/VisDunneRight/gd-comp-eval/assets/2694345/e972d83a-5f0f-4d3a-a9a2-ab9c5d85227d)

**Comment by Turokhunter** [comment]
Fixed issue with site rerouting.
